name: build-windows

on:
  - push

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    env:
        VCPKG_ROOT: ${{ github.workspace }}\vcpkg

    steps:
      - uses: actions/checkout@v1
      - uses: lukka/get-cmake@latest
      - uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
            pkgs: folly hyperscan
            triplet: x64-windows-static
            token: ${{ github.token }}
            github-binarycache: true
      - uses: xmake-io/github-action-setup-xmake@master
        with:
            xmake-version: latest
    
      - name: clone submodule
        run: git submodule update --init --recursive
    
      - name: build project
        run: xmake -y -vD

      - name: Upload binaries to release (main)
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/build/windows/x64/release/pal-plugin-loader.dll
          asset_name: pal-plugin-loader.dll
          tag: "0.0.0-nightly"
          overwrite: true
          body: "This build automatically created by github action, corresponding to commit id ${{ github.sha }}."

