name: build-windows

on:
  - push

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    env:
        VCPKG_ROOT: ${{ github.workspace }}\vcpkg

    steps:
      - uses: actions/checkout@v1
      - uses: lukka/get-cmake@latest
      - uses: johnwason/vcpkg-action@v6
        id: vcpkg
        with:
            pkgs: folly hyperscan
            triplet: x64-windows
            token: ${{ github.token }}
            github-binarycache: true
      - uses: xmake-io/github-action-setup-xmake@master
        with:
            xmake-version: latest
    
      - name: clone submodule
        run: git submodule update --init --recursive
    
      - name: build project
        run: xmake -y -vD

